---
- name: Create a ec2 instance
  hosts: localhost
  tasks:
    - name: Create ec2 m5.xlarge instance
      amazon.aws.ec2_instance:
        name: "{{ key_name }}"
        key_name: demo-oe-mh
        instance_type: m5.xlarge
        image_id: ami-05969be345d4c5c67
        wait: true
        exact_count: 1
        network_interfaces:
          - assign_public_ip: true
        tags:
          type: {{ type_ec2 }}
          purpose: {{purpose_ec2}}
        vpc_subnet_id: subnet-05d9f1634c64f64db
        security_group: aws-test-sg
        region: us-east-1
        volumes:
          - device_name: /dev/sda1
            ebs:
              volume_size: 20
              delete_on_termination: true
